### ISSUE TITLE
جواب سوالات به زبان سی‌شارپ

### ISSUE THREAD

**Issue by HamidMolareza** [modos/quera-answers#2]
سلام
منم جواب سوالاتی (که به مرور) حل میکنم رو توی این [مخزن](https://github.com/HamidMolareza/QueraProblems) قرار میدم.

[مخزن شما](https://github.com/HamidMolareza/QueraProblems#related) رو هم اضافه کردم.

زبون اصلی سی‌شارپ هستش. اگر کسی لازم داشت لطفا بهش معرفی کنید.

ممنون.

**Comment by modos** [comment]
سلام
اضافه کردم
